require 'rake'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = Dir.glob('spec/**/*_spec.rb')
  t.rspec_opts = '--format documentation'
end

task :run, [:filename] do |_, args|
  filename = args[:filename] || 'inputs/input'
  sh "ruby bin/run_aoc.rb #{filename}"
end

task default: :spec
